replicaCount: 1

image:
  repository: ghcr.io/ashah-sg/octopus-workshop-instruqt-argo/sample.frontend
  tag: 25.4.2
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull-secret

service:
  type: ClusterIP
  port: 81
